db.url=${DB_URL:jdbc:postgresql://postgres:5432/bank}
db.username=${DB_USERNAME:bankuser}
db.password=${DB_PASSWORD:bankpass}
hibernate.show_sql=${HIBERNATE_SHOW_SQL:false}
hibernate.hbm2ddl.auto=${HIBERNATE_HBM2DDL_AUTO:update}